IdMaker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
    path('pak_id_card', include("myapp.urls")),
    path('balaji_id_card', include("myapp.urls")),
    path('temp/', include("myapp.urls")),
    path('study-meta/', include("study.urls")),
    #path('idcard/', include('myapp.urls', namespace='idcard')),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'
urlpatterns = [
    path('', views.idcard_home),
    path('pak_id_card', views.pak_idcard),
    path('balaji_id_card', views.balaji_idcard),
    path('temp/',views.temp,name='temp'),
    path('pak_idcard_download/<int:pk>/', views.pak_idcard_download, name='pak_idcard_download'),
    path('balaji_idcard_download/<int:pk>/', views.balaji_idcard_download, name='balaji_idcard_download'),
]

study/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index ),
    path('books/',views.books ),
    path('notes/',views.notes ),
    path('previous-year-paper/',views.previous_year_paper ),
    ]

myapp/models.py
from django.db import models


class Pak_IdCard(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    name = models.CharField(max_length=255)
    father_name = models.CharField(max_length=255)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    image = models.ImageField(upload_to='idcards')


class Template(models.Model):
    template=models.ImageField(upload_to='templates')


class Balaji_IdCard(models.Model):
    name = models.CharField(max_length=255)
    father_name = models.CharField(max_length=255)
    course=models.CharField(max_length=10)
    dob=models.CharField(max_length=40)
    address=models.CharField(max_length=300)
    state=models.CharField(max_length=40)
    image=models.ImageField(upload_to='idcards')
    mobile=models.IntegerField(max_length=10)

study/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from .models import Pak_IdCard,Balaji_IdCard


class PakCardForm(forms.ModelForm):
    class Meta:
        model = Pak_IdCard
        fields = ('name', 'father_name', 'gender', 'image')
        widgets = {
            'image': forms.ClearableFileInput(attrs={'class': 'image_class'})
        }



class BalajiCardForm(forms.ModelForm):
    class Meta:
        model = Balaji_IdCard
        fields = ('name', 'father_name', 'course','dob','address','state','image','mobile')
        widgets = {
            'image': forms.ClearableFileInput(attrs={'class': 'image_class'})
        }

myapp/views.py
from django.shortcuts import render,HttpResponse
from .forms import PakCardForm,BalajiCardForm
from django.http import FileResponse
from .models import Pak_IdCard,Template,Balaji_IdCard
from .idmaker import IdMaker
from django.templatetags.static import static
import requests


def pak_idcard(request):
    if request.method == 'POST':
        form = PakCardForm(request.POST, request.FILES)
        if form.is_valid():
            idcard = form.save()
            template=IdMaker.pak_id_card(idcard)
            idcard.image.delete()
            #tempModel= Template(template,pk=idcard.pk)
            #tempModel.save()
            template.save('myapp/static/template/pak/{}.png'.format(idcard.pk))
            return render(request, 'myapp/pak_idcard_download.html', {'idcard': idcard})

    else:
        form = PakCardForm()
    return render(request, 'myapp/pak_id_card.html', {'form': form})


def balaji_idcard(request):
    if request.method == 'POST':
        form = BalajiCardForm(request.POST, request.FILES)
        if form.is_valid():
            idcard = form.save()
            template=IdMaker.balaji_id_card(idcard)
            idcard.image.delete()
            #tempModel= Template(template,pk=idcard.pk)
            #tempModel.save()
            template.save('myapp/static/template/balaji/{}.png'.format(idcard.pk))
            return render(request, 'myapp/balaji_idcard_download.html', {'idcard': idcard})

    else:
        form = BalajiCardForm()
    return render(request, 'myapp/balaji_id_card.html', {'form': form})


def pak_idcard_download(request, pk):
    idcard = Pak_IdCard.objects.get(pk=pk)

    # tempcard=Template.objects.get(pk=pk)
    file = open('myapp/static/template/pak/{}.png'.format(idcard.pk), 'rb')
    # file = open('media/templates/{}'.format(tempcard.template), 'rb')
    response = FileResponse(file)
    response['Content-Disposition'] = 'attachment; filename={}.png'.format(idcard.name)
    return response

def balaji_idcard_download(request, pk):
    idcard = Balaji_IdCard.objects.get(pk=pk)

    # tempcard=Template.objects.get(pk=pk)
    file = open('myapp/static/template/balaji/{}.png'.format(idcard.pk), 'rb')
    # file = open('media/templates/{}'.format(tempcard.template), 'rb')
    response = FileResponse(file)
    response['Content-Disposition'] = 'attachment; filename={}.png'.format(idcard.name)
    return response



def temp(request):
    img_url=static('template/pak_template.png')
    return render(request,"myapp/index1.html", {'img_url':img_url})


def idcard_home(request):
   # image_url1 = "https://i.ibb.co/qx81ryS/balaji-clg.png"
    #image_url2 = "https://i.ibb.co/sm643C0/pak-temp.png"
    #response1 = requests.get(image_url1)
    #response2 = requests.get(image_url2)
    #with open("balaji-clg.png", "wb") as f:
     #   f.write(response1.content)

    #with open("pak-temp.png", "wb") as f:
     #   f.write(response2.content)
    #balaji_temp_url = static('balaji-clg.png')
    #pak_temp_url = static('pak-temp.png')
    return render(request,"myapp/idcard.html")





study/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.templatetags.static import static


def index(request):
    img_url= static('images/26-january.png')
    return render(request,'study/home.html',{'img_url':img_url})


def books(request):
    return HttpResponse("this is a book")


def notes(request):
    return HttpResponse("this is a notes")


def previous_year_paper(request):
    return HttpResponse("this is a previous_year_paper")




myapp/templates/myapp/balaji_id_card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Balaji Id Card </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style_file/style.css' %}">
</head>
<body>
    <div class="main" align="center">
        <h1 align="center">Welcome To Balaji Id Card Maker!</h1><a href="temp/">Link Temp</a>
        <form class = "my_form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
            <div class="generate-button" >


                <input class="button" type="submit" value="Generate Template">
            </div>
            </form>
    </div>
</body>
</html>

myapp/templates/myapp/balaji_idcard_download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>idcard_download.html</title>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style_file/idcard_download.css' %}">
</head>
<body>
    <div class="main">
        <div class="header" align="center">
          <h1 style="color:green;">Congratulations!</h1><h2> Your Card Is Ready For Download</h2>
        </div>
        <div class="container" align="center">
            <div class="card" >
                <img src="{% url 'myapp:balaji_idcard_download' idcard.pk %}" alt="ID card" >
                <a href="{% url 'myapp:balaji_idcard_download' idcard.pk %}" >
                    <div class="download-button">
                    
                        Download ID card<i class="fas fa-download"></i>
                    </div>
                </a>
            </div>
        </div>
        <div class="footer"></div>
    </div>
</body>
</html>

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title }}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bs5/bootstrap.min.css' %}" />
    {% block cssFile %}{% endblock cssFile %}
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="#">Tech Solve Bhawani</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">IdCard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">#Categories</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      <main class="container">
         {% block content %}{% endblock content %}
      </main>
      <footer></footer>
    <script src="{% static 'bs5/bootstrap.min.js' %}"> </script>
</body>
</html>

myapp/templates/myapp/idcard.html
{% extends 'myapp/base.html' %}
{% block title %}Home Page {% endblock title %}
{% load static %}
{% block cssFile %}
    
{% endblock cssFile %}
{% block content %}
<h1 class="my-4"> Id Card  </h1>
<div class="row">
  <div class="col-md-4">
    <div class="card">

      <img src="{% static 'template/balaji/balaji_homepage.png' %}" alt="image1">

      <a href="balaji_id_card"> <button>Create<span>&rarr;</span></button></a>
    </div>
 </div>
 <div class="col-md-4">
  <div class="card" >
    <img src="{% static 'template/pak/pak_homepage.png' %}" alt="image2">
   <a href="pak_id_card" > <button>Create<span>&rarr;</span></button></a>
  </div>
</div>

<div class="col-md-4">
  <div class="card">

    <img src="{% static 'template/balaji/balaji_homepage.png' %}" alt="image1">

    <a href="balaji_id_card"> <button>Create<span>&rarr;</span></button></a>
  </div>
</div>
<div class="col-md-4">
<div class="card" >
  <img src="{% static 'template/pak/pak_homepage.png' %}" alt="image2">
 <a href="pak_id_card" > <button>Create<span>&rarr;</span></button></a>
</div>
</div>


</div>
{% endblock content %}


myapp/templates/myapp/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Free</title>
</head>
<body>

<h1>This is a {{ img_url }}</h1>
<img src="{{ img_url }}" width="400px" height="250px" align="center">
<a href="/" >Back To Page</a>
</body>
</html>

myapp/templates/myapp/pak_id_card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello world</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style_file/style.css' %}">
</head>
<body>
    <div class="main" align="center">
        <h1 align="center">Welcome To Free Fake Id Card Maker!</h1><a href="temp/">Link Temp</a>
        <form class = "my_form" method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                {{ form.as_p }}
            <div class="generate-button" >


                <input class="button" type="submit" value="Generate Template">
            </div>
            </form>
    </div>
</body>
</html>

myapp/templates/myapp/pak_idcard_download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>idcard_download.html</title>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style_file/idcard_download.css' %}">
</head>
<body>
    <div class="main">
        <div class="header" align="center">
            <h1>Download Your Pakistan Id Card</h1>
        </div>
        <div class="container" align="center">
            <div class="card" >
                <img src="{% url 'myapp:pak_idcard_download' idcard.pk %}" alt="ID card" >
                <a href="{% url 'myapp:pak_idcard_download' idcard.pk %}" >
                <div class="download-button">
                    Download ID card<i class="fas fa-download"></i>
                </div>
                    </a>
            </div>
        </div>
        <div class="footer"></div>
    </div>
</body>
</html>

study/templates/study/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

study/templates/study/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Study-Meta</title>
    <link rel="stylesheet" href="study/style_file/books/home.css">
    <style>
        *{
            margin:0;
            padding:0;
          }
    </style>
</head>
<body>
  <div class="main">
      <div class="header" style="width:100%;height:10%;background:orange;">
          <h1 style="width:100%;height:200px;text-align:center;font-size:100px;padding-top:50px">STUDY-META</h1>

      </div>
      <div class="container">

      </div>
      <div class="footer"></div>
  </div>
</body>
</html>